### ISSUE TITLE
Get all the students of all the classes (regardless of classes and groups)

### ISSUE THREAD

**Issue by alkalinan** [TheSoftwareFactory/DLearnHelsinki-backend#59]
In order to link student to different class, the front end needs to have the list of all the student from all the class. We do not care about classes or groups so only a list of student infos would be perfect. 
`[
{
student_id : 1,
student_name : balblab, 
etc
},
{
...
},
....
]`  

this is basically a select all student for you. this should be only on teacher side (maybe research but we don't care). **GET :: teachers/1/students/**

**Comment by DenisRylow** [comment]
Request is complete.
