### ISSUE TITLE
Clean local backend is slow 

### ISSUE THREAD

**Issue by esaaksvu** [TheSoftwareFactory/DLearnHelsinki-backend#71]
It seems that backend is slow even though it isn't stressed anyhow. I had local backend setup in cleanly installed virtual machine and requests were roughly 5 to 10 seconds each. In some pages frontend makes multiple requests which leads to even greater loading times. I'll continue investigate.

**Comment by Whippler** [comment]
yah, still takes ~5seconds to load groups, and additional ~5seconds to load students for the groups.
http://puu.sh/yl5Fo/d67b40886b.png

**Comment by mihassin** [comment]
This was due to BCrypt function call on every request
