### ISSUE TITLE
end_date in survey table is not return anymore, causing a lot of bugs

### ISSUE THREAD

**Issue by alkalinan** [TheSoftwareFactory/DLearnHelsinki-backend#86]
With **https://.../webapi/teachers/1/classes/8/surveys** for example.
![capture d ecran 2017-11-21 a 10 51 38](https://user-images.githubusercontent.com/19858911/33063105-234c56fa-ceaa-11e7-8b75-7692c3ef9950.png)

the column "end_start" is no more return, this cause a lot of problem in the frontend

**Comment by Whippler** [comment]
Might be fixed, what page uses this method?
